run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    # Core correctness linters — catches real bugs, not style nits
    - govet          # Go vet examines Go source code
    - typecheck      # Type checking
    - staticcheck    # Static analysis
    - gosimple       # Simplify code
    - ineffassign    # Detect ineffectual assignments
    - unused         # Check for unused code
    - gofmt          # Format check
    - goimports      # Import formatting

    # TODO: Re-enable these progressively as codebase matures
    # - errcheck       # Check for unchecked errors
    # - gocritic       # Comprehensive Go source code linter
    # - revive         # Fast, configurable, extensible, flexible linter
    # - stylecheck     # Style conventions
    # - gocyclo        # Cyclomatic complexity
    # - errorlint      # Error wrapping issues
    # - unconvert      # Remove unnecessary conversions
    # - unparam        # Find unused function parameters

linters-settings:
  staticcheck:
    checks: ["all"]

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-dirs:
    - vendor
    - test/fixtures
