entitymetadata:
    schemaversion: ""
    attributes: {}
    migratedat: null
    migratedfrom: ""
id: loom-ye2mh
type: bug
title: 'Port mismatch: loom listens on 8081 but compose maps 8080'
description: Loom API binds to :8081 (main.go:161) but docker-compose exposes 8080:8080. The UI is unreachable on the host. Either change the app to listen on 8080 or fix the compose port mapping to 8080:8081.
status: open
priority: 1
projectid: loom
assignedto: ""
blockedby: []
blocks: []
relatedto: []
parent: ""
children: []
tags: []
context:
    agent_id: agent-1771534515-Product Manager (Default)
    close_reason: ""
    conversation_session_id: 7b8b550d-7776-4d7b-bf9f-1b80f799f055
    dispatch_count: "1"
    dispatch_history: '["agent-1771534515-Product Manager (Default)","agent-1771534515-Product Manager (Default)","agent-1771534515-Product Manager (Default)","agent-1771534515-Product Manager (Default)","agent-1771534515-Product Manager (Default)","agent-1771534515-Product Manager (Default)","agent-1771534515-Product Manager (Default)","agent-1771534515-Product Manager (Default)","agent-1771534515-Product Manager (Default)","agent-1771534515-Product Manager (Default)","agent-1771534515-Product Manager (Default)","agent-1771534515-Product Manager (Default)","agent-1771534515-Product Manager (Default)","agent-1771534515-Product Manager (Default)","agent-1771534515-Product Manager (Default)","agent-1771534515-Product Manager (Default)","agent-1771534515-Product Manager (Default)","agent-1771534515-Product Manager (Default)","agent-1771534515-Product Manager (Default)","agent-1771534515-Product Manager (Default)"]'
    error_history: '[{"timestamp":"2026-02-23T21:07:30.240408744Z","error":"LLM call failed on iteration 3: unexpected status code 502: {\"error\":{\"message\":\"all providers failed\",\"type\":\"server_error\",\"code\":null}}\n","dispatch":1}]'
    last_run_at: "2026-02-23T21:07:30Z"
    last_run_error: |
        LLM call failed on iteration 3: unexpected status code 502: {"error":{"message":"all providers failed","type":"server_error","code":null}}
    loop_detected: "false"
    loop_detected_reason: ""
    loop_detection_reason: Repeated rate limit errors (6 attempts) - exhausted provider quota
    progress_summary: No progress data
    provider_id: tokenhub
    ralph_blocked_at: ""
    ralph_blocked_reason: ""
    redispatch_requested: "true"
    redispatch_requested_at: "2026-02-23T19:33:47Z"
    revert_status: not_attempted
    terminal_reason: ""
duedate: null
milestoneid: ""
estimatedtime: 0
createdat: 2026-02-07T03:19:16Z
updatedat: 2026-02-23T21:07:30.240424025Z
closedat: null
